-- Create race table for F1 races
CREATE TABLE IF NOT EXISTS race (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round INTEGER,
    race_name VARCHAR(255),
    circuit_name VARCHAR(255),
    location VARCHAR(100),
    country VARCHAR(100),
    date VARCHAR(20),
    season INTEGER DEFAULT 2026,
    status VARCHAR(50) DEFAULT 'SCHEDULED',
    driver_id BIGINT,
    position INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_race_season ON race(season);
CREATE INDEX IF NOT EXISTS idx_race_date ON race(date);
CREATE INDEX IF NOT EXISTS idx_race_status ON race(status);
