-- DeltaBox Neon Schema + Seed Data
-- Generated from Flyway migrations V0-V11
-- Run once on fresh Neon database

BEGIN;

-- ========================================
-- V0: Users table
-- ========================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL DEFAULT '',
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(50) DEFAULT 'USER',
    google_sub VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- ========================================
-- V1: Historical F1 Data Tables (1950-2026)
-- ========================================
CREATE TABLE IF NOT EXISTS historical_season (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER UNIQUE NOT NULL,
    total_rounds INTEGER,
    champion_driver_id BIGINT,
    champion_constructor_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_historical_season_year ON historical_season(year);

CREATE TABLE IF NOT EXISTS historical_race (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season_year INTEGER NOT NULL,
    round INTEGER NOT NULL,
    race_name VARCHAR(255),
    circuit_name VARCHAR(255),
    circuit_country VARCHAR(255),
    race_date DATE,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (season_year) REFERENCES historical_season(year),
    UNIQUE(season_year, round)
);

CREATE INDEX IF NOT EXISTS idx_historical_race_season ON historical_race(season_year);
CREATE INDEX IF NOT EXISTS idx_historical_race_circuit ON historical_race(circuit_name);

CREATE TABLE IF NOT EXISTS historical_driver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_ref VARCHAR(255) UNIQUE NOT NULL,
    full_name VARCHAR(255),
    code VARCHAR(10),
    nationality VARCHAR(100),
    date_of_birth DATE,
    total_wins INTEGER DEFAULT 0,
    total_poles INTEGER DEFAULT 0,
    total_championships INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_historical_driver_ref ON historical_driver(driver_ref);
CREATE INDEX IF NOT EXISTS idx_historical_driver_code ON historical_driver(code);

CREATE TABLE IF NOT EXISTS historical_constructor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    constructor_ref VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255),
    nationality VARCHAR(100),
    total_wins INTEGER DEFAULT 0,
    total_championships INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_historical_constructor_ref ON historical_constructor(constructor_ref);

CREATE TABLE IF NOT EXISTS historical_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    constructor_id BIGINT,
    grid_position INTEGER,
    finish_position INTEGER,
    points DECIMAL(5,2),
    status VARCHAR(100),
    fastest_lap_time VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (race_id) REFERENCES historical_race(id),
    FOREIGN KEY (driver_id) REFERENCES historical_driver(id),
    FOREIGN KEY (constructor_id) REFERENCES historical_constructor(id),
    UNIQUE(race_id, driver_id)
);

CREATE INDEX IF NOT EXISTS idx_historical_result_race ON historical_result(race_id);
CREATE INDEX IF NOT EXISTS idx_historical_result_driver ON historical_result(driver_id);
CREATE INDEX IF NOT EXISTS idx_historical_result_constructor ON historical_result(constructor_id);
CREATE INDEX IF NOT EXISTS idx_historical_result_finish ON historical_result(finish_position);

CREATE TABLE IF NOT EXISTS ingestion_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year_start INTEGER,
    year_end INTEGER,
    total_races BIGINT DEFAULT 0,
    total_results BIGINT DEFAULT 0,
    total_drivers BIGINT DEFAULT 0,
    total_constructors BIGINT DEFAULT 0,
    years_ingested TEXT,
    status VARCHAR(50),
    error_message TEXT,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS driver_circuit_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id BIGINT NOT NULL,
    circuit_name VARCHAR(255),
    races_at_circuit INTEGER DEFAULT 0,
    avg_finish_position DECIMAL(5,2),
    wins_at_circuit INTEGER DEFAULT 0,
    poles_at_circuit INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (driver_id) REFERENCES historical_driver(id),
    UNIQUE(driver_id, circuit_name)
);

CREATE TABLE IF NOT EXISTS constructor_circuit_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    constructor_id BIGINT NOT NULL,
    circuit_name VARCHAR(255),
    races_at_circuit INTEGER DEFAULT 0,
    avg_finish_position DECIMAL(5,2),
    wins_at_circuit INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (constructor_id) REFERENCES historical_constructor(id),
    UNIQUE(constructor_id, circuit_name)
);

CREATE TABLE IF NOT EXISTS season_driver_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER,
    driver_id BIGINT NOT NULL,
    races_completed INTEGER DEFAULT 0,
    avg_finish_position DECIMAL(5,2),
    total_points DECIMAL(5,2),
    wins INTEGER DEFAULT 0,
    poles INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (driver_id) REFERENCES historical_driver(id),
    UNIQUE(year, driver_id)
);

-- ========================================
-- V2: Qualifying and Standings tables
-- ========================================
CREATE TABLE IF NOT EXISTS historical_qualifying (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id BIGINT NOT NULL,
    driver_id BIGINT NOT NULL,
    constructor_id BIGINT,
    position INTEGER,
    q1 VARCHAR(20),
    q2 VARCHAR(20),
    q3 VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (race_id) REFERENCES historical_race(id),
    FOREIGN KEY (driver_id) REFERENCES historical_driver(id),
    FOREIGN KEY (constructor_id) REFERENCES historical_constructor(id),
    UNIQUE(race_id, driver_id)
);

CREATE INDEX IF NOT EXISTS idx_historical_qualifying_race ON historical_qualifying(race_id);
CREATE INDEX IF NOT EXISTS idx_historical_qualifying_driver ON historical_qualifying(driver_id);

CREATE TABLE IF NOT EXISTS historical_driver_standings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    driver_id BIGINT NOT NULL,
    position INTEGER,
    points DECIMAL(8,2),
    wins INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (driver_id) REFERENCES historical_driver(id),
    UNIQUE(year, driver_id)
);

CREATE INDEX IF NOT EXISTS idx_historical_driver_standings_year ON historical_driver_standings(year);
CREATE INDEX IF NOT EXISTS idx_historical_driver_standings_driver ON historical_driver_standings(driver_id);

CREATE TABLE IF NOT EXISTS historical_constructor_standings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year INTEGER NOT NULL,
    constructor_id BIGINT NOT NULL,
    position INTEGER,
    points DECIMAL(8,2),
    wins INTEGER DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (constructor_id) REFERENCES historical_constructor(id),
    UNIQUE(year, constructor_id)
);

CREATE INDEX IF NOT EXISTS idx_historical_constructor_standings_year ON historical_constructor_standings(year);
CREATE INDEX IF NOT EXISTS idx_historical_constructor_standings_constructor ON historical_constructor_standings(constructor_id);

-- ========================================
-- V3: Add google_sub column
-- ========================================
ALTER TABLE users ADD COLUMN IF NOT EXISTS google_sub VARCHAR(255);
CREATE INDEX IF NOT EXISTS idx_users_google_sub ON users(google_sub);

-- ========================================
-- V4: Add username column
-- ========================================
ALTER TABLE users ADD COLUMN IF NOT EXISTS username VARCHAR(50) UNIQUE NOT NULL DEFAULT '';

UPDATE users
SET username = SUBSTRING(email, 1, POSITION('@' IN email) - 1)
WHERE username = '' OR username IS NULL;

-- ========================================
-- V5: Update existing usernames
-- ========================================
UPDATE users
SET username = SUBSTRING(email, 1, POSITION('@' IN email) - 1)
WHERE username = '' OR username IS NULL;

-- ========================================
-- V7: Team table
-- ========================================
CREATE TABLE IF NOT EXISTS team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    nationality VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_team_name ON team(name);

-- ========================================
-- V8: Driver table
-- ========================================
CREATE TABLE IF NOT EXISTS driver (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10),
    name VARCHAR(255),
    nationality VARCHAR(100),
    team_id BIGINT,
    team VARCHAR(255),
    season INTEGER DEFAULT 2026,
    points DOUBLE PRECISION DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(code, season),
    FOREIGN KEY (team_id) REFERENCES team(id)
);

CREATE INDEX IF NOT EXISTS idx_driver_code ON driver(code);
CREATE INDEX IF NOT EXISTS idx_driver_season ON driver(season);
CREATE INDEX IF NOT EXISTS idx_driver_team_id ON driver(team_id);

-- ========================================
-- V9: Race table
-- ========================================
CREATE TABLE IF NOT EXISTS race (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round INTEGER,
    race_name VARCHAR(255),
    circuit_name VARCHAR(255),
    location VARCHAR(100),
    country VARCHAR(100),
    date VARCHAR(20),
    season INTEGER DEFAULT 2026,
    status VARCHAR(50) DEFAULT 'SCHEDULED',
    driver_id BIGINT,
    position INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_race_season ON race(season);
CREATE INDEX IF NOT EXISTS idx_race_date ON race(date);
CREATE INDEX IF NOT EXISTS idx_race_status ON race(status);

-- ========================================
-- V10: Seed 2026 Season Data
-- ========================================
INSERT INTO team (name, nationality) VALUES
('Red Bull Racing', 'Austrian'),
('Ferrari', 'Italian'),
('McLaren', 'British'),
('Mercedes', 'German'),
('Aston Martin', 'British'),
('Alpine F1 Team', 'French'),
('Williams', 'British'),
('RB F1 Team', 'Italian'),
('Stake F1 Team Kick Sauber', 'Swiss'),
('Haas F1 Team', 'American');

INSERT INTO driver (code, name, nationality, team, points, season) VALUES
('VER', 'Max Verstappen', 'Dutch', 'Red Bull Racing', 0, 2026),
('TSU', 'Yuki Tsunoda', 'Japanese', 'Red Bull Racing', 0, 2026),
('LEC', 'Charles Leclerc', 'Monegasque', 'Ferrari', 0, 2026),
('HAM', 'Lewis Hamilton', 'British', 'Ferrari', 0, 2026),
('NOR', 'Lando Norris', 'British', 'McLaren', 0, 2026),
('PIA', 'Oscar Piastri', 'Australian', 'McLaren', 0, 2026),
('RUS', 'George Russell', 'British', 'Mercedes', 0, 2026),
('BOT', 'Valtteri Bottas', 'Finnish', 'Mercedes', 0, 2026),
('ALO', 'Fernando Alonso', 'Spanish', 'Aston Martin', 0, 2026),
('STR', 'Lance Stroll', 'Canadian', 'Aston Martin', 0, 2026),
('GAM', 'Gabriel Bortoleto', 'Brazilian', 'Alpine F1 Team', 0, 2026),
('DEV', 'Dev Singh', 'Indian', 'Alpine F1 Team', 0, 2026),
('ALB', 'Alexander Albon', 'Thai', 'Williams', 0, 2026),
('SAR', 'Carlos Sainz', 'Spanish', 'Williams', 0, 2026),
('HAD', 'Isack Hadjar', 'French', 'RB F1 Team', 0, 2026),
('MAR', 'Maryanne Ndiaye', 'Senegalese', 'RB F1 Team', 0, 2026),
('HUL', 'Nico Hulkenberg', 'German', 'Stake F1 Team Kick Sauber', 0, 2026),
('BOR', 'Gabriel Bortoleto', 'Brazilian', 'Stake F1 Team Kick Sauber', 0, 2026),
('OCO', 'Esteban Ocon', 'French', 'Haas F1 Team', 0, 2026),
('BEA', 'Oliver Bearman', 'British', 'Haas F1 Team', 0, 2026);

INSERT INTO race (round, race_name, circuit_name, location, country, date, season, status) VALUES
(1, 'Australian Grand Prix', 'Albert Park Grand Prix Circuit', 'Melbourne', 'Australia', '2026-03-15', 2026, 'COMPLETED'),
(2, 'Chinese Grand Prix', 'Shanghai International Circuit', 'Shanghai', 'China', '2026-03-22', 2026, 'COMPLETED'),
(3, 'Japanese Grand Prix', 'Suzuka Circuit', 'Suzuka', 'Japan', '2026-04-05', 2026, 'COMPLETED'),
(4, 'Miami Grand Prix', 'Miami International Autodrome', 'Miami', 'USA', '2026-05-03', 2026, 'SCHEDULED'),
(5, 'Emilia Romagna Grand Prix', 'Autodromo Enzo e Dino Ferrari', 'Imola', 'Italy', '2026-05-17', 2026, 'SCHEDULED'),
(6, 'Monaco Grand Prix', 'Circuit de Monaco', 'Monte Carlo', 'Monaco', '2026-05-24', 2026, 'SCHEDULED'),
(7, 'Spanish Grand Prix', 'Circuit de Barcelona-Catalunya', 'Barcelona', 'Spain', '2026-06-07', 2026, 'SCHEDULED'),
(8, 'Canadian Grand Prix', 'Circuit Gilles Villeneuve', 'Montreal', 'Canada', '2026-06-14', 2026, 'SCHEDULED'),
(9, 'Austrian Grand Prix', 'Red Bull Ring', 'Spielberg', 'Austria', '2026-06-28', 2026, 'SCHEDULED'),
(10, 'British Grand Prix', 'Silverstone Circuit', 'Silverstone', 'UK', '2026-07-05', 2026, 'SCHEDULED'),
(11, 'Belgian Grand Prix', 'Circuit de Spa-Francorchamps', 'Spa', 'Belgium', '2026-07-26', 2026, 'SCHEDULED'),
(12, 'Hungarian Grand Prix', 'Hungaroring', 'Budapest', 'Hungary', '2026-08-02', 2026, 'SCHEDULED'),
(13, 'Dutch Grand Prix', 'Circuit Zandvoort', 'Zandvoort', 'Netherlands', '2026-08-30', 2026, 'SCHEDULED'),
(14, 'Italian Grand Prix', 'Autodromo di Monza', 'Monza', 'Italy', '2026-09-06', 2026, 'SCHEDULED'),
(15, 'Azerbaijan Grand Prix', 'Baku City Circuit', 'Baku', 'Azerbaijan', '2026-09-20', 2026, 'SCHEDULED'),
(16, 'Singapore Grand Prix', 'Marina Bay Street Circuit', 'Singapore', 'Singapore', '2026-10-04', 2026, 'SCHEDULED'),
(17, 'Japanese Grand Prix', 'Suzuka Circuit', 'Suzuka', 'Japan', '2026-10-10', 2026, 'SCHEDULED'),
(18, 'Qatar Grand Prix', 'Lusail International Circuit', 'Lusail', 'Qatar', '2026-11-08', 2026, 'SCHEDULED'),
(19, 'United States Grand Prix', 'Circuit of the Americas', 'Austin', 'USA', '2026-11-22', 2026, 'SCHEDULED'),
(20, 'Mexico City Grand Prix', 'Autodromo Hermanos Rodriguez', 'Mexico City', 'Mexico', '2026-11-29', 2026, 'SCHEDULED'),
(21, 'Abu Dhabi Grand Prix', 'Yas Marina Circuit', 'Abu Dhabi', 'UAE', '2026-12-06', 2026, 'SCHEDULED'),
(22, 'Saudi Arabian Grand Prix', 'Jeddah Corniche Circuit', 'Jeddah', 'Saudi Arabia', '2026-12-13', 2026, 'SCHEDULED');

-- ========================================
-- V11: Seed Race Results (Completed Races 1-3)
-- ========================================
-- Only run after historical data ingestion via Ergast API.
-- These inserts may fail if historical_driver/historical_race
-- rows don't exist yet. Safe to skip on fresh install.
-- Remove the DO $$ block below once historical data is ingested.

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM historical_race LIMIT 1) THEN
    INSERT INTO historical_result (race_id, driver_id, constructor_id, grid_position, finish_position, points, status)
    VALUES
      (1, 6, 3, 1, 1, 25.0, 'Finished'),
      (1, 1, 1, 2, 2, 18.0, 'Finished'),
      (1, 3, 2, 3, 3, 15.0, 'Finished'),
      (1, 7, 4, 4, 4, 12.0, 'Finished'),
      (1, 5, 3, 5, 5, 10.0, 'Finished'),
      (1, 4, 2, 6, 6, 8.0, 'Finished'),
      (1, 9, 5, 7, 7, 6.0, 'Finished'),
      (1, 13, 7, 8, 8, 4.0, 'Finished'),
      (1, 2, 1, 9, 9, 2.0, 'Finished'),
      (1, 15, 8, 10, 10, 1.0, 'Finished');

    INSERT INTO historical_result (race_id, driver_id, constructor_id, grid_position, finish_position, points, status)
    VALUES
      (2, 1, 1, 1, 1, 25.0, 'Finished'),
      (2, 3, 2, 2, 2, 18.0, 'Finished'),
      (2, 6, 3, 3, 3, 15.0, 'Finished'),
      (2, 5, 3, 4, 4, 12.0, 'Finished'),
      (2, 7, 4, 5, 5, 10.0, 'Finished'),
      (2, 4, 2, 6, 6, 8.0, 'Finished'),
      (2, 8, 4, 7, 7, 6.0, 'Finished'),
      (2, 10, 5, 8, 8, 4.0, 'Finished'),
      (2, 17, 9, 9, 9, 2.0, 'Finished'),
      (2, 19, 10, 10, 10, 1.0, 'Finished');

    INSERT INTO historical_result (race_id, driver_id, constructor_id, grid_position, finish_position, points, status)
    VALUES
      (3, 1, 1, 1, 1, 25.0, 'Finished'),
      (3, 6, 3, 2, 2, 18.0, 'Finished'),
      (3, 4, 2, 3, 3, 15.0, 'Finished'),
      (3, 5, 3, 4, 4, 12.0, 'Finished'),
      (3, 7, 4, 5, 5, 10.0, 'Finished'),
      (3, 3, 2, 6, 6, 8.0, 'Finished'),
      (3, 9, 5, 7, 7, 6.0, 'Finished'),
      (3, 2, 1, 8, 8, 4.0, 'Finished'),
      (3, 11, 6, 9, 9, 2.0, 'Finished'),
      (3, 18, 9, 10, 10, 1.0, 'Finished');
  END IF;
END $$;

COMMIT;
